### PR TITLE
/api/v1/profiles Endpoint

### LINKED ISSUE #130: Backend Profile Implementation
I will implement the User Profile support for backend.

### PR DESCRIPTION
**Pull request by cburakaygun**
Hello,

This PR contains the implementation of **Profile** . Related documentation can be found [here](https://github.com/bounswe/bounswe2018group7/wiki/API-Endpoints#profiles).

Fixes #130

### CODE REVIEW

**Comment by cburakaygun** [comment]
Hello @eneskosr 

Thanks for the feedback. I pushed a commit to fix the problem. Can you check again?

**Comment by eneskosr** [comment]
Hi @cburakaygun 

Thanks for the quick fix. It looks fine, now. I have tested all functionalities and they are working as expected.

**Comment by cburakaygun** [comment]
You can **approve** the changes by clicking "Review changes" button under [Files changed](https://github.com/bounswe/bounswe2018group7/pull/137/files) section.

**Comment by eneskosr** [comment]
Done

**Pull request merged**
